details:
  namespace: student119-bookinfo-prd
  image: ghcr.io/62130500119/bookinfo-details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
ingress:
  host: bookinfo.opsta.net
  path: "/student119/details(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2

  